name = "healthhatch-web-oauth-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

# Add these secrets via: wrangler secret put GITHUB_CLIENT_ID
# wrangler secret put GITHUB_CLIENT_SECRET
# wrangler secret put REDIRECT_URI
# wrangler secret put SITE_URL

